VERSION = "1.24"
APP = "Auto Neutron"
ORG = "Numerlor"
APPID = f"{ORG}|{APP}|{VERSION}"

# script data
SHIP_STATS = {'RConst': {
    'class1': 11,
    'class2': 10,
    'class3': 8,
    'class4': 10,
    'class5': 12,
},

    'SConst': {
        'size2': 2.00,
        'size3': 2.15,
        'size4': 2.30,
        'size5': 2.45,
        'size6': 2.60,
        'size7': 2.75,
        'size8': 2.90,
    },

    'MaxUsage': {'int_hyperdrive_size2_class1': 0.60,
                 'int_hyperdrive_size2_class2': 0.60,
                 'int_hyperdrive_size2_class3': 0.60,
                 'int_hyperdrive_size2_class4': 0.80,
                 'int_hyperdrive_size2_class5': 0.90,
                 'int_hyperdrive_size3_class1': 1.20,
                 'int_hyperdrive_size3_class2': 1.20,
                 'int_hyperdrive_size3_class3': 1.20,
                 'int_hyperdrive_size3_class4': 1.50,
                 'int_hyperdrive_size3_class5': 1.80,
                 'int_hyperdrive_size4_class1': 2.00,
                 'int_hyperdrive_size4_class2': 2.00,
                 'int_hyperdrive_size4_class3': 2.00,
                 'int_hyperdrive_size4_class4': 2.50,
                 'int_hyperdrive_size4_class5': 3.00,
                 'int_hyperdrive_size5_class1': 3.30,
                 'int_hyperdrive_size5_class2': 3.30,
                 'int_hyperdrive_size5_class3': 3.30,
                 'int_hyperdrive_size5_class4': 4.10,
                 'int_hyperdrive_size5_class5': 5.00,
                 'int_hyperdrive_size6_class1': 5.30,
                 'int_hyperdrive_size6_class2': 5.30,
                 'int_hyperdrive_size6_class3': 5.30,
                 'int_hyperdrive_size6_class4': 6.60,
                 'int_hyperdrive_size6_class5': 8.00,
                 'int_hyperdrive_size7_class1': 8.50,
                 'int_hyperdrive_size7_class2': 8.50,
                 'int_hyperdrive_size7_class3': 8.50,
                 'int_hyperdrive_size7_class4': 10.60,
                 'int_hyperdrive_size7_class5': 12.80,
                 },
    'OptimalMass': {'int_hyperdrive_size2_class1': 48,
                    'int_hyperdrive_size2_class2': 54,
                    'int_hyperdrive_size2_class3': 60,
                    'int_hyperdrive_size2_class4': 75,
                    'int_hyperdrive_size2_class5': 90,
                    'int_hyperdrive_size3_class1': 80,
                    'int_hyperdrive_size3_class2': 90,
                    'int_hyperdrive_size3_class3': 100,
                    'int_hyperdrive_size3_class4': 125,
                    'int_hyperdrive_size3_class5': 150,
                    'int_hyperdrive_size4_class1': 280,
                    'int_hyperdrive_size4_class2': 315,
                    'int_hyperdrive_size4_class3': 350,
                    'int_hyperdrive_size4_class4': 438,
                    'int_hyperdrive_size4_class5': 525,
                    'int_hyperdrive_size5_class1': 560,
                    'int_hyperdrive_size5_class2': 630,
                    'int_hyperdrive_size5_class3': 700,
                    'int_hyperdrive_size5_class4': 875,
                    'int_hyperdrive_size5_class5': 1050,
                    'int_hyperdrive_size6_class1': 960,
                    'int_hyperdrive_size6_class2': 1080,
                    'int_hyperdrive_size6_class3': 1200,
                    'int_hyperdrive_size6_class4': 1500,
                    'int_hyperdrive_size6_class5': 1800,
                    'int_hyperdrive_size7_class1': 1440,
                    'int_hyperdrive_size7_class2': 1620,
                    'int_hyperdrive_size7_class3': 1800,
                    'int_hyperdrive_size7_class4': 2250,
                    'int_hyperdrive_size7_class5': 2700,
                    },

    'Booster':
        {
            'int_guardianfsdbooster_size1': 4.0,
            'int_guardianfsdbooster_size2': 6.0,
            'int_guardianfsdbooster_size3': 7.75,
            'int_guardianfsdbooster_size4': 9.25,
            'int_guardianfsdbooster_size5': 10.5,
        }
}
