[tool.poetry]
name = "Auto_Neutron"
version = "2.0.0b"
description = "An automatic neutron route plotter for Elite Dangerous"
authors = ["Numerlor <numerlor@users.noreply.github.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "3.9.*"

PySide6 = "~6.2.0"
requests = "~2.26"

[tool.poetry.dev-dependencies]
# Base tools
flake8 = "~3.9"

flake8-annotations = "~2.6"
flake8-bandit = "~2.1"
flake8-bugbear = "21.9.1"
flake8-docstrings = "~1.6"
flake8-isort = "~4.0"
flake8-print = "~4.0"
isort = "~5.9"
black = "21.9b0"
pre-commit = "~2.15"
pyinstaller = "~4.5"
taskipy = "~1.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
atomic = true
profile = "black"
multi_line_output = 3
line_length = 88
include_trailing_comma = true
use_parentheses = true
known_first_party = ["auto_neutron", "__feature__"]

[tool.black]
target-version = ["py39"]

[tool.taskipy.tasks]
start = "python main.py"
lint = "pre-commit run --all-files"
pyside-pyi = "pyside6-genpyi all --feature snake_case true_property"
