[tool.poetry]
name = "Auto_Neutron"
version = "2.0.0b"
description = "An automatic neutron route plotter for Elite Dangerous"
authors = ["Numerlor <numerlor@users.noreply.github.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "3.9.*"

ahk = "~0.9"
pyperclip = "~1.8"
PySide6 = "~6.1.3"
requests = "~2.24"
playsound = {url="https://github.com/TaylorSMarks/playsound/archive/9cf4af20caa5ae8586f88b65659681b24f0c4e69.zip"}

[tool.poetry.dev-dependencies]
# Base tools
flake8 = "~3.9"

flake8-annotations = "~2.6"
flake8-docstrings = "~1.6"
flake8-print = "~=3.1"
flake8-import-order = "~=0.18"
isort = "~5.9"
black = "21.9b0"
pyinstaller = "~=3.6, >=3.6"
taskipy = "~=1.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
atomic = true
profile = "black"
multi_line_output = 3
line_length = 88
include_trailing_comma = true
use_parentheses = true
known_first_party = ["auto_neutron", "__feature__"]

[tool.black]
target-version = ["py39"]

[tool.taskipy.tasks]
start = "python main.py"
lint = "python -m flake8"
pyside-pyi = "pyside6-genpyi all --feature snake_case true_property"